### ISSUE TITLE
PA Review: User signup, login and logout. Demo login.

### ISSUE THREAD

**Issue by michaelzhu1** [michaelzhu1/Zoomm#2]

**Comment by s-pangburn** [comment]
Hi Michael,

Please update your wiki with the live Heroku link!

**Comment by michaelzhu1** [comment]
Hi Stephen,

I just updated it. Sorry about that. 

Michael

**Comment by s-pangburn** [comment]
No worries! Site is looking pretty good so far (good job styling the modal!)

### Things to fix

1. Input field text should be white. Right now it's very hard to read. Same with the "Welcome to Zoomm!" header and the nav links.

2. Have a link within the modal to switch between login and signup forms

3. Maybe center the modal header or otherwise make it a little nicer. Definitely change text color to something more readable.

4. Demo login doesn't work

5. Improve styling on navbar when logged in.

6. Have errors display in red or yellow or some other eye-catching color

### Things that would be nice

1. It would be nice if the modal appeared either in the center of the screen or directly underneath the login and signup buttons. Underneath the logo is a little awkward as it feels I have to reach a bit with the mouse.

2. Either the login and signup links should close the modal when it is open or you should be able to click outside of the modal to close it. Right now, there is no clear way to close the modal if you made a mistake opening it. You can click on HOME, but that's a little counterintuitive and people won't always want to go to the homepage to close the modal.

3. Maybe try to find a more appealing font. This can wait, though.

**Comment by s-pangburn** [comment]
Hi Michael,

The login form header text still needs to be more visible and the form still needs to be centered on the screen before I can sign off that this feature is complete. The link text to switch forms should also be more descriptive, and preferably mention the words "Login" or "Signup".

Please let me know when you have this feature finished so I can review it again!
